os: linux
dist: bionic

language: python
python:
  - "3.6"
cache: pip

services:
  - postgresql

env:
  - DATABASE_URI=postgres://postgres:@localhost:5432/test

before_script:
  - psql -c 'create database test;' -U postgres

# command to install dependencies
install: "pip3 install -r requirements.txt"

# command to run tests
script: nosetests

after_success:
  - codecov
  - pylint service